title: Name Space
tagline: iOS internals, reverse engineering, low-level systems

description: >-
  Write-ups on iOS internals, reverse engineering, and low-level systems programming.

url: "https://lavochkaa.github.io"

github:
  username: lavochkaa

twitter:
  username: name_space1

social:
  name: Name Space
  email: name.space.std@outlook.com
  fediverse_handle:
  links:
    - https://github.com/lavochkaa
    - https://t.me/name_space1
    - https://twitter.com/name_space1

theme_mode: dark

avatar: /assets/img/avatar.png
